#!/usr/bin/env bash

error() {
	echo "$1"
	exit 1
}

if [[ "$1" == "-l" ]]; then
	LENGTH="$2"
else
	error "$0 -l [pass length]"
fi

if command -v openssl >/dev/null; then
	openssl rand -base64 $LENGTH
elif command -v uuidgen >/dev/null; then
	uuidgen | sed 's/[-]//g' | head -c $LENGTH; echo
else
	echo "Your system does not have openssl or uuidgen."
	exit 1
fi