#!/usr/bin/env bash

error() {
  echo "$1"
  exit 1
}

echo "https://github.com/quiww/scripts"

if [[ "$1" == "--help" ]]; then
  error "Usage: $0 {--detailed}"
elif [[ "$1" == "--detailed" ]]; then
  curl -L myip.bsd.cafe
else
  curl -s https://myip.bsd.cafe/raw && printf "\n"
fi
